export const DB_COLUMNS = {
  EVENTS: [
    'id',
    'title',
    'start_datetime',
    'end_datetime',
    'all_day',
    'category',
    'description',
    'created_at',
    'updated_at',
  ],
  TASKS: [
    'id',
    'title',
    'execution_date',
    'completed',
    'order',
    'actual_time',
    'estimated_time',
    'created_at',
    'updated_at',
  ],
  MONTHLY_GOALS: [
    'id',
    'title',
    'target_date',
    'year',
    'month',
    'created_at',
    'updated_at',
  ],
  YEARLY_GOALS: [
    'id',
    'title',
    'target_date',
    'year',
    'created_at',
    'updated_at',
  ],
  WEEKLY_GOALS: [
    'id',
    'title',
    'year',
    'week_start_date',
    'created_at',
    'updated_at',
  ],
  USER_SETTINGS: [
    'id',
    'birthday',
    'default_calendar_view',
    'week_start_day',
    'morning_review_time',
    'evening_review_time',
    'created_at',
    'updated_at',
  ],
} as const
