export const DB_COLUMNS = {
  EVENTS: [
    'id',
    'title',
    'start_datetime',
    'end_datetime',
    'all_day',
    'category',
    'description',
    'created_at',
    'updated_at',
  ],
  TASKS: [
    'id',
    'title',
    'execution_date',
    'completed',
    'order',
    'actual_time',
    'created_at',
    'updated_at',
  ],
  MONTHLY_GOALS: [
    'id',
    'title',
    'year',
    'month',
    'achieved',
    'created_at',
    'updated_at',
  ],
  YEARLY_GOALS: [
    'id',
    'title',
    'year',
    'achieved',
    'created_at',
    'updated_at',
  ],
  WEEKLY_GOALS: [
    'id',
    'title',
    'year',
    'week_start_date',
    'achieved',
    'created_at',
    'updated_at',
  ],
  USER_SETTINGS: [
    'id',
    'birthday',
    'default_calendar_view',
    'week_start_day',
    'morning_review_time',
    'evening_review_time',
    'barcelona_ical_url',
    'created_at',
    'updated_at',
  ],
  BUCKET_LIST_CATEGORIES: [
    'id',
    'name',
    'created_at',
    'updated_at',
  ],
  BUCKET_LIST_ITEMS: [
    'id',
    'title',
    'category_id',
    'target_year',
    'achieved_date',
    'completed',
    'order',
    'created_at',
    'updated_at',
  ],
  WISHLIST_CATEGORIES: [
    'id',
    'name',
    'created_at',
    'updated_at',
  ],
  WISHLIST_ITEMS: [
    'id',
    'name',
    'category_id',
    'target_year',
    'price',
    'order',
    'created_at',
    'updated_at',
  ],
  SUBSCRIPTIONS: [
    'id',
    'name',
    'monthly_price',
    'billing_cycle',
    'next_billing_date',
    'start_date',
    'cancellation_url',
    'active',
    'created_at',
    'updated_at',
  ],
  DAILY_LOGS: [
    'id',
    'log_date',
    'diary',
    'created_at',
    'updated_at',
  ],
  DEV_YEARLY_GOALS: [
    'id',
    'title',
    'year',
    'achieved',
    'created_at',
    'updated_at',
  ],
  DEV_MONTHLY_GOALS: [
    'id',
    'title',
    'year',
    'month',
    'achieved',
    'created_at',
    'updated_at',
  ],
  DEV_WEEKLY_GOALS: [
    'id',
    'title',
    'year',
    'week_start_date',
    'achieved',
    'created_at',
    'updated_at',
  ],
  DEV_TASKS: [
    'id',
    'title',
    'project_id',
    'type',
    'execution_date',
    'completed',
    'order',
    'actual_time',
    'created_at',
    'updated_at',
  ],
  VISION_CATEGORIES: [
    'id',
    'name',
    'created_at',
    'updated_at',
  ],
  VISION_ITEMS: [
    'id',
    'title',
    'category_id',
    'order',
    'created_at',
    'updated_at',
  ],
  TRANSACTION_CATEGORIES: [
    'id',
    'type',
    'name',
    'created_at',
    'updated_at',
  ],
  TRANSACTIONS: [
    'id',
    'date',
    'type',
    'name',
    'amount',
    'category_id',
    'is_fixed',
    'created_at',
    'updated_at',
  ],
} as const
